#!/bin/bash

# get load averages
IFS=" " read LOAD1 LOAD5 LOAD15 <<<$(/bin/cat /proc/loadavg | awk '{ print $1,$2,$3 }')
# get free memory
IFS=" " read USED FREE TOTAL <<<$(free -htm | grep "Mem" | awk {'print $3,$4,$2'})
# get processes
PROCESS=`ps -eo user=|sort|uniq -c | awk '{ print $2 " " $1 }'`
PROCESS_ALL=`echo "$PROCESS"| awk {'print $2'} | awk '{ SUM += $1} END { print SUM }'`
PROCESS_ROOT=`echo "$PROCESS"| grep root | awk {'print $2'}`
PROCESS_USER=`echo "$PROCESS"| grep -v root | awk {'print $2'} | awk '{ SUM += $1} END { print SUM }'`

W="\e[0;39m"
R="\e[1;31m"
B="\e[0;39m"

echo -e "
$W  Distro........: $B`cat /etc/*release | grep "PRETTY_NAME" | cut -d "=" -f 2- | sed 's/"//g'`
$W  Kernel........: $B`uname -sr`

$W  Uptime........: $B`uptime -p`
$W  Load..........: $R$LOAD1$B (1m) $R$LOAD5$B (5m) $R$LOAD15$B (15m)
$W  Processes.....:$B root ($R$PROCESS_ROOT$B), user ($R$PROCESS_USER$B) | ($R$PROCESS_ALL$B) total

$W  CPU...........: $B`cat /proc/cpuinfo | grep "model name" | cut -d ' ' -f3- | awk {'print $0'} | head -1`
$W  Memory........: $R$USED$B used, $R$FREE$B free, $R$TOTAL$B in total$W"
