#!/bin/bash

printf "\nzpool status:\n"
zpool status -x | sed -e 's/^/  /'

printf "\nzpool usage:\n"
zpool list -Ho name,cap,size | awk '{ printf("%-10s%+3s used out of %+5s\n", $1, $2, $3); }' | sed -e 's/^/  /'
