#!/bin/bash

logfile='/var/log/fail2ban.log*'
mapfile -t lines < <(zgrep -hioP '(\[[a-z-]+\]) (ban|unban)' $logfile | sort | uniq -c)
jails=($(printf -- '%s\n' "${lines[@]}" | zgrep -oP '\[\K[^\]]+' | sort | uniq))

out=""
for jail in ${jails[@]}; do
    bans=$(printf -- '%s\n' "${lines[@]}" | zgrep -iP "[[:digit:]]+ \[$jail\] ban" | awk '{print $1}')
    unbans=$(printf -- '%s\n' "${lines[@]}" | zgrep -iP "[[:digit:]]+ \[$jail\] unban" | awk '{print $1}')
    diff=$(($bans-$unbans))
    out+=$(printf "$jail, %+3s bans, %+3s unbans, %+3s active" $bans $unbans $diff)"\n"
done

printf "\nfail2ban status (monthly):\n"
printf "$out" | column -ts $',' | sed -e 's/^/  /'
